// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/17/2024, 4:22:25 PM
const configMerger = require("/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/plugins/**/*.{js,ts,mjs}","/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/composables/**/*.{js,ts,mjs}","/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/utils/**/*.{js,ts,mjs}","/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kevintjhia/Documents/projects/work/untitled-folder/test-reportapp/app.config.{js,ts,mjs}"] }));

module.exports = config
